# Site settings
name: Caixing Su
location: Hobart
company: CMCC
position: Data Analyst
github: https://github.com/srichonmore/srichonmore.github.io
facebook: https://www.facebook.com/profile.php?id=100010676380006
phone: 0434068708
email: caixingsu1990@gmail.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

incremental: true

